11 automate spatial feature specification
DeshpandeLab/SpaceMarkers pull request #14
Opened 2024-07-25 00:41 UTC by dimalvovs

refactor:
- eliminate `featureNames=NULL`  since checking with regex `"."` does the same and is shorter
- simplify and deduplicate `if  else` and messages
- add tests to ensure most cases are covered (Seurat is not well defined so it's not covered)
- introduce helper getters that each work with own input type
- add test objects for cogaps and bayestme

ready to automate spatial feature specification now.

2024-07-25 15:39 UTC, atuldeshpande requested changes
Thank you for this refactoring! It is much easier to follow the logic for each method option even if some method may just be two lines of code.

Please see some comments and suggestions.

2024-07-25 15:39 UTC, atuldeshpande commented on man/cogaps_result.Rd
Need to delete the corresponding cogaps_result.rda from the data folder? See build check errors.

2024-07-25 15:39 UTC, atuldeshpande commented on R/preprocessing.R
> +    featureNames <- intersect(featureNames,colnames(spFeatures))
There could be a case where user lists 6 patterns but we find only 5 in the object. How should we handle that?
1. Message which reports that we did not find all patterns, and are continuing with the rest.
2. Error which reports the specific patterns we did not find, and ask user to check input.
I note that this scenario may be more common in non-pipeline use cases.

2024-07-25 15:51 UTC, dimalvovs commented on R/preprocessing.R
> +        spFeatures <- getBtme(filePath)
sure, shall the method also become "Anndata"?

2024-07-25 15:53 UTC, dimalvovs commented on R/preprocessing.R
> +    featureNames <- intersect(featureNames,colnames(spFeatures))
Makes sense!

2024-07-25 15:54 UTC, dimalvovs commented on man/cogaps_result.Rd
Sure, I did not delete as there is currently a non-merged pull request that does just that. Merging that will resolve the build check error.

2024-07-25 15:56 UTC, atuldeshpande commented on R/preprocessing.R
> +        spFeatures <- getBtme(filePath)
I think when we actually add generic Anndata support, we can change method == "BayesTME" to method in c("BayesTME", "Anndata")?

2024-07-25 18:29 UTC, dimalvovs commented on man/cogaps_result.Rd
It did not help. I wonder how build-check has worked on the main branch where there is cogaps_result.rda present and no documentation for it.

2024-07-25 18:32 UTC, dimalvovs commented on R/preprocessing.R
> +        spFeatures <- getBtme(filePath)
agree, let's change when we actually add generic Anndata support!

2024-07-25 18:32 UTC, dimalvovs commented on R/preprocessing.R
> +    featureNames <- intersect(featureNames,colnames(spFeatures))
addressed in [cd2ab20](https://github.com/DeshpandeLab/SpaceMarkers/pull/14/commits/cd2ab2089f614a6855336d2f91f07be6515f5b07)

2024-07-25 18:40 UTC, dimalvovs commented on man/cogaps_result.Rd
deleted in [b836616](https://github.com/DeshpandeLab/SpaceMarkers/pull/14/commits/b8366163488c6669d57c814286c1b27bdd4d33b4)

2024-07-30 13:57 UTC, atuldeshpande approved these changes

2024-07-30 13:58 UTC, merged